### ISSUE TITLE
This should never happen

### ISSUE THREAD

**Issue by soufianeEssabbane** [johnno1962/SwiftRegex#4]
Hi, i'm having a problem I don't understand why i'm getting this error :  
 if dispatch_semaphore_wait(lock, dispatch_time(DISPATCH_TIME_NOW, Int64(10 \* NSEC_PER_MSEC))) != 0 {
            fatalError("This should never happen")
        }

and my app crashes like all the time by displaying this message in logs. can you please tell me what does it mean ? why this should never happen ? when it happen ? thank you very much

**Comment by johnno1962** [comment]
Are you sure this is to do with SwiftRegex? I don’t remember that code.

**Comment by nuclearace** [comment]
@johnno1962 Yeah this is related to my library which uses a heavily modified version of this one. He opened an issue there as well. Go ahead and close this one

**Comment by johnno1962** [comment]
OK thanks

**Comment by soufianeEssabbane** [comment]
Thanks @johnno1962  thanks @nuclearace :+1:
